"""initial_schema

Revision ID: cc07e5f15af1
Revises: 
Create Date: 2026-06-05 14:48:38.165868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc07e5f15af1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workspace_path', sa.String(length=1024), nullable=False),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('github_repo_url', sa.String(length=512), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'archived', 'failed')", name='ck_projects_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('idx_projects_slug', ['slug'], unique=False)
        batch_op.create_index('idx_projects_status', ['status'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sessions',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'running', 'completed', 'failed', 'cancelled')", name='ck_sessions_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('idx_sessions_project', ['project_id'], unique=False)

    op.create_table('messages',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name='ck_messages_role'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_messages_session', ['session_id', 'created_at'], unique=False)

    op.create_table('runs',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('trigger_message_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='running', nullable=False),
    sa.Column('current_agent', sa.String(length=32), nullable=True),
    sa.Column('current_step', sa.Integer(), server_default='0', nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('graph_state', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("status IN ('running', 'success', 'failed', 'cancelled')", name='ck_runs_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index('idx_runs_session', ['session_id'], unique=False)
        batch_op.create_index('idx_runs_status', ['status'], unique=False)

    op.create_table('git_operations',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('commit_hash', sa.String(length=64), nullable=True),
    sa.Column('commit_message', sa.Text(), nullable=True),
    sa.Column('remote_url', sa.String(length=512), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("operation IN ('init', 'add', 'commit', 'push', 'create_repo')", name='ck_git_operations_operation'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('git_operations', schema=None) as batch_op:
        batch_op.create_index('idx_git_ops_project', ['project_id'], unique=False)

    op.create_table('memory_entries',
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('importance', sa.Integer(), server_default='5', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("memory_type IN ('architecture', 'convention', 'dependency', 'failure', 'preference')", name='ck_memory_entries_memory_type'),
    sa.CheckConstraint('importance BETWEEN 1 AND 10', name='ck_memory_entries_importance'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_entries', schema=None) as batch_op:
        batch_op.create_index('idx_memory_key', ['key'], unique=False)
        batch_op.create_index('idx_memory_project', ['project_id'], unique=False)
        batch_op.create_index('idx_memory_type', ['memory_type'], unique=False)

    op.create_table('plans',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('architecture_notes', sa.Text(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('folder_structure', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'approved', 'in_progress', 'complete')", name='ck_plans_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index('idx_plans_run', ['run_id'], unique=False)

    op.create_table('run_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'seq', name='uq_run_events_run_id_seq')
    )
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.create_index('idx_run_events_run', ['run_id', 'seq'], unique=False)

    op.create_table('architecture_decisions',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('consequences', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='accepted', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('proposed', 'accepted', 'superseded')", name='ck_architecture_decisions_status'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('architecture_decisions', schema=None) as batch_op:
        batch_op.create_index('idx_adr_project', ['project_id'], unique=False)

    op.create_table('plan_steps',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('step_type', sa.String(length=20), nullable=False),
    sa.Column('files_spec', sa.JSON(), nullable=True),
    sa.Column('commands', sa.JSON(), nullable=True),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'complete', 'failed', 'skipped')", name='ck_plan_steps_status'),
    sa.CheckConstraint("step_type IN ('scaffold', 'file', 'command', 'verify', 'git')", name='ck_plan_steps_step_type'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_steps', schema=None) as batch_op:
        batch_op.create_index('idx_plan_steps_plan', ['plan_id', 'step_order'], unique=False)

    op.create_table('commands_executed',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('plan_step_id', sa.String(length=36), nullable=True),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('cwd', sa.String(length=1024), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('agent', sa.String(length=32), server_default='terminal', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plan_step_id'], ['plan_steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commands_executed', schema=None) as batch_op:
        batch_op.create_index('idx_commands_run', ['run_id'], unique=False)

    op.create_table('file_changes',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('plan_step_id', sa.String(length=36), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('diff', sa.Text(), nullable=True),
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("action IN ('create', 'edit', 'delete')", name='ck_file_changes_action'),
    sa.ForeignKeyConstraint(['plan_step_id'], ['plan_steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_changes', schema=None) as batch_op:
        batch_op.create_index('idx_file_changes_project', ['project_id', 'file_path'], unique=False)
        batch_op.create_index('idx_file_changes_run', ['run_id'], unique=False)

    op.create_table('errors',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('command_id', sa.String(length=36), nullable=True),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('context_files', sa.JSON(), nullable=True),
    sa.Column('resolved', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('fix_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['commands_executed.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('errors', schema=None) as batch_op:
        batch_op.create_index('idx_errors_run', ['run_id'], unique=False)

    settings = sa.table(
        "settings",
        sa.column("key", sa.String),
        sa.column("value", sa.Text),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        settings,
        [
            {"key": "llm_model", "value": '"gpt-4o"'},
            {"key": "auto_push_github", "value": "false"},
            {"key": "max_debug_retries", "value": "5"},
            {"key": "milestone_commits", "value": "true"},
            {"key": "command_allowlist_enabled", "value": "false"},
        ],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('errors', schema=None) as batch_op:
        batch_op.drop_index('idx_errors_run')

    op.drop_table('errors')
    with op.batch_alter_table('file_changes', schema=None) as batch_op:
        batch_op.drop_index('idx_file_changes_run')
        batch_op.drop_index('idx_file_changes_project')

    op.drop_table('file_changes')
    with op.batch_alter_table('commands_executed', schema=None) as batch_op:
        batch_op.drop_index('idx_commands_run')

    op.drop_table('commands_executed')
    with op.batch_alter_table('plan_steps', schema=None) as batch_op:
        batch_op.drop_index('idx_plan_steps_plan')

    op.drop_table('plan_steps')
    with op.batch_alter_table('architecture_decisions', schema=None) as batch_op:
        batch_op.drop_index('idx_adr_project')

    op.drop_table('architecture_decisions')
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.drop_index('idx_run_events_run')

    op.drop_table('run_events')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index('idx_plans_run')

    op.drop_table('plans')
    with op.batch_alter_table('memory_entries', schema=None) as batch_op:
        batch_op.drop_index('idx_memory_type')
        batch_op.drop_index('idx_memory_project')
        batch_op.drop_index('idx_memory_key')

    op.drop_table('memory_entries')
    with op.batch_alter_table('git_operations', schema=None) as batch_op:
        batch_op.drop_index('idx_git_ops_project')

    op.drop_table('git_operations')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('idx_runs_status')
        batch_op.drop_index('idx_runs_session')

    op.drop_table('runs')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_messages_session')

    op.drop_table('messages')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_sessions_project')

    op.drop_table('sessions')
    op.drop_table('settings')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('idx_projects_status')
        batch_op.drop_index('idx_projects_slug')

    op.drop_table('projects')
    # ### end Alembic commands ###
